#!/usr/bin/env bash
# This script displays "Best School" 10 times using a for loop.

# The string to be displayed
message="Best School"

# Using a for loop to display the message 10 times
for ((i = 1; i <= 10; i++)); do
	echo "$message"
done
