#!/usr/bin/env bash
# This script displays number 1 to 20 at 4, 9, & 17 they display different bad lucks

i=0
while [ $i -le 20 ];
	do
		echo "$i"
		case $i in 
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
		esac
		(( i++ ))
		done
